### ISSUE TITLE
New version of Docker Compose: 1.26.2

### ISSUE THREAD

**Issue by crummy** [tiangolo/docker-with-compose#19]
When I run `docker-compose -version` on my Mac I get:
```
1.26.2, build eefe0d31
```

Inside the tiangolo/docker-with-compose container I get:
```
1.26.0
```
I have an issue using contexts that only repros in the container, and I assume it's from the version difference. When I built the container manually, i.e. ran `docker:latest` then ran `apk add --no-cache py3-pip python3-dev libffi-dev openssl-dev curl gcc libc-dev make && pip3 install docker-compose` my issue disappeared.

Can you rebuild your docker image, to get the newest docker-compose included?

**Comment by xtccc** [comment]
I think you can update by yourself , just follow the offical guide ,rm the old version ,  download the new , use `ln -s` link them ,
[offical_install_link](https://docs.docker.com/compose/install/)
 by the way , I update the docker-compose too ,because the old versin doesn't support  the `init : true`

**Comment by tiangolo** [comment]
Thanks! I just updated the way dependencies are handled so that I'll get Dependabot updates automatically. And of course, now it has the latest version. :rocket: :tada:
