### ISSUE TITLE
Bitbucket Pipelines: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed

### ISSUE THREAD

**Issue by sboesch** [tiangolo/docker-with-compose#32]
First of all, thanks a lot for this project.

Just wanted to let you (and others) know that the latest version (`latest` / `2022-11-10`) doesn't work in Bitbucket Pipelines anymore:

```
+ docker-compose build
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 2.6s done
#1 creating container buildx_buildkit_default 0.0s done
#1 ERROR: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed
------
 > [internal] booting buildkit:
------
Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed
```

I switched back to version `2021-09-18`, which works fine.
Not sure if this is anything you can fix at all.

**Comment by tiangolo** [comment]
Hmmm, strange, not sure what that error might mean. I also don't use Bitbucket Pipelines myself so I wouldn't have a way to debug it, I wouldn't easily face the same problem. 🤔

But if you discover anything else, please let me know.

**Comment by Ousret** [comment]
Hi,

We faced something of the same importance. (gitlab-ci, docker executor) The tag:latest induced a series of breaking changes.
Our problem is regarding generating `docker-stack.yml` for our clusters at work.

e.g. 

```bash
docker-compose -f docker-compose.yml -f docker-compose.deploy.yml \
config > docker-stack.yml
```

- `version: '3.8'` is not present on the generated stack.yml (the target host fallback to `version: 1` which is problematic. even though it is on our (input) files.
- volumes descriptions have changed unexpectedly so there are re-created (not found)

before (stack.yml)
```yaml
volumes:
  app-jwt-store: {}
```

after:
```yaml
volumes:
  app-jwt-store:
    name: stack-name_app-jwt-store
```

Probably due to upstream changes. Not docker-compose as it is pinned in the image.

**Comment by tiangolo** [comment]
@Ousret did you get the same error or a different error?

If it's different, then please create another issue, with a self-contained example to replicate the problem.
